[package]
name = "ntrulp"
version = "0.1.3"
edition = "2021"
publish = true
authors = ["Rinat hicc0rus@gmail.com"]
readme = "README.md"
license = "ISC"
license-file = "LICENSE"
keywords = ["NTRU Prime", "NTRU", "rust", "ideal-lattice-based", "cryptography"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.16.0"
rand = "0.8.5"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "key_gen"
harness = false

[[bench]]
name = "chipher"
harness = false

[[bench]]
name = "rq"
harness = false
