#[cfg(feature = "ntrulpr1013")]
use crate::params::params1013::{P, SEEDS_BYTES};
#[cfg(feature = "ntrulpr1277")]
use crate::params::params1277::{P, SEEDS_BYTES};
#[cfg(feature = "ntrulpr653")]
use crate::params::params653::{P, SEEDS_BYTES};
#[cfg(feature = "ntrulpr761")]
use crate::params::params761::{P, SEEDS_BYTES};
#[cfg(feature = "ntrulpr857")]
use crate::params::params857::{P, SEEDS_BYTES};
#[cfg(feature = "ntrulpr953")]
use crate::params::params953::{P, SEEDS_BYTES};
